import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Bike, CheckCircle2, Clock3, MapPin, Navigation, PackageCheck, Plus, RefreshCw, Route, Truck, UserRound, X } from 'lucide-react';
import api from '../services/api';
import { can, readSession } from '../services/session';
import { isNativeLocationAvailable, nativeTrackingStatus, startNativeTracking, stopNativeTracking } from '../services/nativeLocation';
import { isNativePushAvailable, registerNativePush } from '../services/nativePush';

type Driver = { id:number; nome:string; email:string; telefone?:string; veiculo?:string; placa?:string; status_entrega:string };
type Delivery = { id:number; numero:string; cliente:string; telefone?:string; endereco?:string; total:number; status:string; data:string; entrega?: { status:string; observacao?:string; atribuido_em?:string; retirado_em?:string; latitude?:number; longitude?:number; localizacao_atualizada_em?:string; entregador?:Driver } };

const money = (value:number) => value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const shortNumber = (value:string) => value.split('-').pop() || value;
const stateStyle:Record<string,string> = { Pronto:'bg-amber-100 text-amber-800', atribuida:'bg-blue-100 text-blue-700', em_rota:'bg-purple-100 text-purple-700' };

export default function Deliveries(){
  const session=readSession(); const manager=can(session,'entregas.gerenciar'); const isDriver=session?.perfil==='entregador';
  const [orders,setOrders]=useState<Delivery[]>([]); const [drivers,setDrivers]=useState<Driver[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<number|null>(null); const [error,setError]=useState(''); const [driverModal,setDriverModal]=useState(false); const [tracking,setTracking]=useState<number|null>(null); const [focusedOrder,setFocusedOrder]=useState<number|null>(null);
  const [form,setForm]=useState({nome:'',email:'',senha:'',telefone:'',veiculo:'Moto',placa:'',perfil:'entregador'}); const watches=useRef<Map<number,number>>(new Map());
  const load=useCallback(async()=>{try{if(isDriver){const orderResult=await api.get('/entregas/painel');setOrders(orderResult.data);setDrivers([]);}else{const [orderResult,driverResult]=await Promise.all([api.get('/entregas/painel'),api.get('/entregas/entregadores')]);setOrders(orderResult.data);setDrivers(driverResult.data);}setError('');}catch(err:any){setError(err.response?.data?.detail||'Não foi possível carregar as entregas.');}finally{setLoading(false);}},[isDriver]);
  useEffect(()=>{load();nativeTrackingStatus().then(state=>{if(state.active&&state.orderId)setTracking(state.orderId);}).catch(()=>undefined);const timer=window.setInterval(load,8000);const activeWatches=watches.current;return()=>{clearInterval(timer);activeWatches.forEach(id=>navigator.geolocation.clearWatch(id));};},[load]);
  useEffect(()=>{if(!isDriver||!isNativePushAvailable())return;let active=true;const openOrder=(orderId?:number)=>{if(!active||!orderId)return;setFocusedOrder(orderId);void load();};registerNativePush().then(data=>openOrder(data.orderId)).catch(err=>{if(active)setError(err?.message||'Não foi possível ativar as notificações deste aparelho.');});const listener=(event:Event)=>openOrder((event as CustomEvent<{orderId?:number}>).detail?.orderId);window.addEventListener('ritmesaPushOpen',listener);return()=>{active=false;window.removeEventListener('ritmesaPushOpen',listener);};},[isDriver,load]);
  useEffect(()=>{if(!focusedOrder)return;const card=document.getElementById(`entrega-${focusedOrder}`);if(card){card.scrollIntoView({behavior:'smooth',block:'center'});const timer=window.setTimeout(()=>setFocusedOrder(null),5000);return()=>clearTimeout(timer);}},[focusedOrder,orders]);
  const metrics=useMemo(()=>({ready:orders.filter(o=>o.status==='Pronto'&&!o.entrega?.entregador).length,assigned:orders.filter(o=>o.entrega?.status==='atribuida').length,route:orders.filter(o=>o.entrega?.status==='em_rota').length}),[orders]);
  async function assign(orderId:number,driverId:string){if(!driverId)return;setBusy(orderId);try{await api.post(`/entregas/${orderId}/atribuir`,{entregador_id:Number(driverId)});await load();}catch(err:any){setError(err.response?.data?.detail||'Não foi possível atribuir a entrega.');}finally{setBusy(null);}}
  async function accept(orderId:number){setBusy(orderId);try{await api.post(`/entregas/${orderId}/aceitar`);await load();}catch(err:any){setError(err.response?.data?.detail||'Não foi possível aceitar a entrega.');await load();}finally{setBusy(null);}}
  async function status(orderId:number,value:string,observation?:string){setBusy(orderId);try{await api.put(`/entregas/${orderId}/status`,{status:value,observacao:observation});if(value==='entregue'||value==='falha')stopLocation(orderId);await load();}catch(err:any){setError(err.response?.data?.detail||'Não foi possível atualizar a entrega.');}finally{setBusy(null);}}
  async function startLocation(orderId:number){
    setError('');
    if(isNativeLocationAvailable()){
      try{await startNativeTracking(orderId);setTracking(orderId);}catch(err:any){setError(err?.message||'Não foi possível iniciar o GPS em segundo plano.');}
      return;
    }
    if(!navigator.geolocation){setError('Este aparelho não oferece localização GPS.');return;}
    if(watches.current.has(orderId))return;
    const id=navigator.geolocation.watchPosition(async pos=>{try{await api.put(`/entregas/${orderId}/localizacao`,{latitude:pos.coords.latitude,longitude:pos.coords.longitude});setTracking(orderId);}catch{setError('Não foi possível enviar sua localização.');}},()=>setError('Autorize o acesso à localização para ativar o rastreamento.'),{enableHighAccuracy:true,maximumAge:15000,timeout:20000});
    watches.current.set(orderId,id);setTracking(orderId);
  }
  async function stopLocation(orderId:number){
    if(isNativeLocationAvailable())await stopNativeTracking().catch(()=>undefined);
    const id=watches.current.get(orderId);if(id!==undefined)navigator.geolocation.clearWatch(id);
    watches.current.delete(orderId);setTracking(current=>current===orderId?null:current);
  }
  async function createDriver(e:React.FormEvent){e.preventDefault();setBusy(-1);try{await api.post('/usuarios',form);setDriverModal(false);setForm({nome:'',email:'',senha:'',telefone:'',veiculo:'Moto',placa:'',perfil:'entregador'});await load();}catch(err:any){setError(err.response?.data?.detail||'Não foi possível cadastrar o entregador.');}finally{setBusy(null);}}
  const directions=(address?:string,provider:'google'|'waze'='google')=>window.open(provider==='waze'?`https://waze.com/ul?q=${encodeURIComponent(address||'')}&navigate=yes`:`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(address||'')}`,'_blank','noopener,noreferrer');
  if(loading)return <div className="p-16 text-center text-slate-500">Carregando expedição...</div>;
  return <div className="min-h-full p-4 md:p-8 lg:p-10 max-w-[1500px] mx-auto">
    <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between mb-7"><div><div className="text-orange-600 font-bold uppercase tracking-[.16em] text-xs flex items-center gap-2"><Truck size={17}/> Expedição e última milha</div><h1 className="text-3xl md:text-4xl font-heading font-bold text-slate-900 mt-2">{isDriver?'Minhas entregas':'Painel de entregas'}</h1><p className="text-slate-500 mt-1">{isDriver?'Retire, navegue e conclua seus pedidos.':'Distribua pedidos prontos e acompanhe quem está na rua.'}</p></div><div className="flex flex-wrap gap-2"><button onClick={load} className="px-4 py-3 rounded-xl bg-white border border-slate-200 font-bold flex gap-2 items-center"><RefreshCw size={18}/>Atualizar</button>{manager&&<button onClick={()=>setDriverModal(true)} className="kds-inverse px-4 py-3 rounded-xl bg-slate-900 text-white font-bold flex gap-2 items-center"><Plus size={18}/>Entregador</button>}</div></header>
    {error&&<div className="mb-5 rounded-xl bg-red-50 border border-red-200 px-4 py-3 text-red-700 flex justify-between"><span>{error}</span><button onClick={()=>setError('')}><X size={18}/></button></div>}
    {!isDriver&&<section className="grid grid-cols-3 gap-2 md:gap-4 mb-6">{[{n:metrics.ready,label:'Prontos',Icon:PackageCheck,c:'text-amber-600'},{n:metrics.assigned,label:'Atribuídos',Icon:Clock3,c:'text-blue-600'},{n:metrics.route,label:'Na rua',Icon:Route,c:'text-purple-600'}].map(({n,label,Icon,c})=><div key={label} className="bg-white border border-slate-200 rounded-2xl p-3 md:p-5 shadow-sm"><span className={`${c} text-xs md:text-sm font-bold flex gap-2 items-center`}><Icon size={18}/>{label}</span><strong className="text-2xl md:text-3xl block mt-2">{n}</strong></div>)}</section>}
    {orders.length===0?<div className="bg-white border border-dashed rounded-3xl py-20 text-center"><CheckCircle2 size={44} className="mx-auto text-emerald-500"/><h2 className="text-xl font-bold mt-3">Nenhuma entrega pendente</h2><p className="text-slate-500 mt-1">A expedição está em dia.</p></div>:<section className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{orders.map(order=>{const deliveryStatus=order.entrega?.status||order.status;const driver=order.entrega?.entregador;return <article id={`entrega-${order.id}`} key={order.id} className={`bg-white border rounded-2xl shadow-sm overflow-hidden transition-all ${focusedOrder===order.id?'border-orange-500 ring-4 ring-orange-200':'border-slate-200'}`}><div className="p-4 bg-slate-50 border-b flex justify-between gap-3"><div><span className="text-xs font-bold text-slate-500">PEDIDO #{shortNumber(order.numero)}</span><h2 className="font-bold text-xl mt-1">{order.cliente}</h2></div><span className={`h-fit rounded-full px-2.5 py-1 text-xs font-bold ${stateStyle[deliveryStatus]||'bg-slate-100 text-slate-600'}`}>{deliveryStatus==='em_rota'?'Em rota':deliveryStatus==='atribuida'?'Atribuído':'Pronto'}</span></div><div className="p-4 space-y-4"><div className="flex gap-3"><MapPin className="text-orange-500 shrink-0" size={20}/><div><p className="text-sm font-semibold text-slate-800">{order.endereco||'Endereço não informado'}</p>{order.telefone&&<p className="text-xs text-slate-500 mt-1">{order.telefone}</p>}</div></div><div className="flex justify-between border-y py-3 text-sm"><span className="text-slate-500">Valor do pedido</span><strong>{money(order.total)}</strong></div>{driver&&<div className="flex items-center gap-3 rounded-xl bg-blue-50 p-3"><div className="w-9 h-9 rounded-full bg-blue-100 text-blue-700 grid place-items-center"><UserRound size={18}/></div><div><strong className="block text-sm">{driver.nome}</strong><span className="text-xs text-slate-500">{driver.veiculo||'Veículo'}{driver.placa?` · ${driver.placa}`:''}</span></div></div>}
      {manager&&!driver&&<select disabled={busy===order.id||order.status!=='Pronto'} onChange={e=>assign(order.id,e.target.value)} className="field"><option value="">Atribuir entregador...</option>{drivers.filter(d=>d.status_entrega!=='em_rota').map(d=><option key={d.id} value={d.id}>{d.nome} · {d.status_entrega==='disponivel'?'Disponível':'Atribuído'}</option>)}</select>}
      {isDriver&&!driver&&order.status==='Pronto'&&<button disabled={busy===order.id} onClick={()=>accept(order.id)} className="kds-inverse w-full py-3 rounded-xl bg-orange-500 text-white font-bold flex justify-center items-center gap-2"><Bike size={19}/>{busy===order.id?'Aceitando...':'Aceitar entrega'}</button>}
      {manager&&driver&&deliveryStatus==='atribuida'&&<button onClick={()=>status(order.id,'aguardando')} className="w-full py-2.5 rounded-xl border border-slate-200 font-semibold text-slate-600">Remover atribuição</button>}
      {(isDriver||manager)&&deliveryStatus==='atribuida'&&<button disabled={busy===order.id} onClick={()=>status(order.id,'em_rota')} className="kds-inverse w-full py-3 rounded-xl bg-orange-500 text-white font-bold flex justify-center items-center gap-2"><Bike size={19}/>Confirmar retirada</button>}
      {(isDriver||manager)&&deliveryStatus==='em_rota'&&<><div className="grid grid-cols-2 gap-2"><button onClick={()=>directions(order.endereco,'google')} className="py-3 rounded-xl bg-blue-50 text-blue-700 border border-blue-200 font-bold flex justify-center items-center gap-2"><Navigation size={18}/>Google Maps</button><button onClick={()=>directions(order.endereco,'waze')} className="py-3 rounded-xl bg-sky-50 text-sky-700 border border-sky-200 font-bold flex justify-center items-center gap-2"><Navigation size={18}/>Waze</button></div>{isDriver&&<button onClick={()=>tracking===order.id?stopLocation(order.id):startLocation(order.id)} className={`w-full py-3 rounded-xl font-bold flex justify-center items-center gap-2 ${tracking===order.id?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-700'}`}><MapPin size={19}/>{tracking===order.id?(isNativeLocationAvailable()?'GPS ativo em segundo plano':'Localização sendo enviada'):'Compartilhar localização'}</button>}<div className="grid grid-cols-2 gap-2"><button onClick={()=>status(order.id,'falha',prompt('Motivo da ocorrência:')||'Não entregue')} className="py-3 rounded-xl bg-red-50 text-red-700 font-bold">Ocorrência</button><button onClick={()=>status(order.id,'entregue')} className="kds-inverse py-3 rounded-xl bg-emerald-600 text-white font-bold">Entregue</button></div></>}
    </div></article>})}</section>}
    {manager&&<section className="mt-8"><h2 className="text-xl font-bold mb-3">Equipe de entrega</h2><div className="flex gap-3 overflow-x-auto pb-2">{drivers.map(d=><div key={d.id} className="shrink-0 w-64 bg-white border rounded-2xl p-4 flex gap-3"><div className="w-10 h-10 rounded-xl bg-orange-100 text-orange-700 grid place-items-center"><Bike size={20}/></div><div><strong className="block">{d.nome}</strong><span className="text-xs text-slate-500">{d.veiculo||'Veículo não informado'}{d.placa?` · ${d.placa}`:''}</span><span className={`block text-xs font-bold mt-1 ${d.status_entrega==='em_rota'?'text-purple-600':'text-emerald-600'}`}>{d.status_entrega==='em_rota'?'Em rota':d.status_entrega==='atribuido'?'Pedido atribuído':'Disponível'}</span></div></div>)}</div></section>}
    {driverModal&&<div className="fixed inset-0 z-[80] bg-slate-950/60 p-4 flex items-center justify-center"><form onSubmit={createDriver} className="bg-white rounded-3xl w-full max-w-lg p-6"><div className="flex justify-between items-start mb-5"><div><h2 className="text-2xl font-bold">Novo entregador</h2><p className="text-sm text-slate-500">Crie o acesso usado no celular.</p></div><button type="button" onClick={()=>setDriverModal(false)} className="p-2 rounded-full bg-slate-100"><X/></button></div><div className="grid md:grid-cols-2 gap-3"><input required className="field md:col-span-2" placeholder="Nome completo" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/><input required type="email" className="field" placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength={8} type="password" className="field" placeholder="Senha inicial" value={form.senha} onChange={e=>setForm({...form,senha:e.target.value})}/><input className="field" placeholder="Telefone" value={form.telefone} onChange={e=>setForm({...form,telefone:e.target.value})}/><input className="field" placeholder="Veículo (Moto, bike...)" value={form.veiculo} onChange={e=>setForm({...form,veiculo:e.target.value})}/><input className="field md:col-span-2" placeholder="Placa (opcional)" value={form.placa} onChange={e=>setForm({...form,placa:e.target.value.toUpperCase()})}/></div><button disabled={busy===-1} className="kds-inverse mt-5 w-full py-3 rounded-xl bg-orange-500 text-white font-bold">Cadastrar entregador</button></form></div>}
  </div>;
}
