import { useState } from 'react';
import { ArrowRight, BarChart3, Check, ChefHat, Menu, PackageCheck, ShoppingBag, X } from 'lucide-react';
import api from '../services/api';

export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [sent, setSent] = useState(false);
  const [sending, setSending] = useState(false);
  const [form, setForm] = useState({ nome: '', estabelecimento: '', telefone: '', email: '', cidade: '', mensagem: '' });

  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    setSending(true);
    try {
      await api.post('/comercial/interesse', form);
      setSent(true);
    } finally {
      setSending(false);
    }
  };

  return (
    <div className="min-h-screen bg-white text-[#10233f]">
      <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/95 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8">
          <a href="#inicio" className="flex items-center gap-2.5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-50 ring-1 ring-slate-200"><img src="/brand/ritmesa-mark.png" alt="" className="h-8 w-8 object-contain" /></span><strong className="text-xl tracking-tight">Ritmesa</strong></a>
          <nav className="hidden items-center gap-7 text-sm font-semibold text-slate-600 md:flex"><a href="#solucoes" className="hover:text-brand-600">Soluções</a><a href="#como-funciona" className="hover:text-brand-600">Como funciona</a><a href="/bisburger" className="hover:text-brand-600">Ver cardápio</a><a href="#contato" className="rounded-xl bg-brand-500 px-4 py-2.5 text-white hover:bg-brand-600">Quero conhecer</a></nav>
          <button onClick={() => setMenuOpen((value) => !value)} className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 md:hidden" aria-label="Abrir menu">{menuOpen ? <X /> : <Menu />}</button>
        </div>
        {menuOpen && <nav className="grid gap-1 border-t border-slate-100 bg-white p-4 text-sm font-semibold md:hidden"><a onClick={() => setMenuOpen(false)} href="#solucoes" className="rounded-xl px-4 py-3">Soluções</a><a onClick={() => setMenuOpen(false)} href="#como-funciona" className="rounded-xl px-4 py-3">Como funciona</a><a href="/bisburger" className="rounded-xl px-4 py-3">Ver cardápio</a><a onClick={() => setMenuOpen(false)} href="#contato" className="rounded-xl bg-brand-500 px-4 py-3 text-center text-white">Quero conhecer</a></nav>}
      </header>

      <main>
        <section id="inicio" className="landing-hero overflow-hidden px-5 pb-20 pt-16 sm:pt-24 lg:px-8 lg:pb-28">
          <div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]">
            <div><span className="inline-flex rounded-full bg-orange-100 px-3 py-1.5 text-xs font-bold uppercase tracking-wider text-brand-700">Tecnologia para food service</span><h1 className="mt-6 max-w-3xl text-4xl font-bold leading-[1.08] tracking-[-.045em] sm:text-6xl">Seu negócio no ritmo certo.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-600">Pedidos, cardápio digital, caixa, estoque e gestão reunidos em uma plataforma simples para restaurantes que querem crescer.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#contato" className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-brand-500 px-6 py-3 font-bold text-white shadow-xl shadow-brand-500/20 hover:bg-brand-600">Quero vender mais <ArrowRight size={19} /></a><a href="/bisburger" className="flex min-h-12 items-center justify-center rounded-xl border border-slate-300 bg-white px-6 py-3 font-bold text-slate-700 hover:bg-slate-50">Conhecer cardápio real</a></div></div>
            <div className="relative"><div className="absolute -inset-10 rounded-full bg-orange-200/35 blur-3xl" /><div className="relative rounded-[28px] border border-slate-200 bg-white p-4 shadow-2xl shadow-slate-900/15"><div className="rounded-2xl bg-[#10233f] p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs text-slate-300">Visão de hoje</p><strong className="mt-1 block text-xl">BisBurger</strong></div><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-300">Operação ativa</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-4"><span className="text-xs text-slate-300">Pedidos</span><strong className="mt-1 block text-2xl">48</strong></div><div className="rounded-xl bg-white/10 p-4"><span className="text-xs text-slate-300">Faturamento</span><strong className="mt-1 block text-2xl">R$ 2,4 mil</strong></div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-4"><ShoppingBag className="text-brand-500" /><strong className="mt-5 block">Cardápio online</strong><span className="mt-1 block text-xs text-slate-500">Bonito em qualquer tela</span></div><div className="rounded-2xl border border-slate-200 p-4"><BarChart3 className="text-brand-500" /><strong className="mt-5 block">Gestão em tempo real</strong><span className="mt-1 block text-xs text-slate-500">Decisões com dados</span></div></div></div></div>
          </div>
        </section>

        <section id="solucoes" className="bg-[#f6f8fb] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><span className="text-sm font-bold text-brand-600">Uma operação conectada</span><h2 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Tudo que o restaurante precisa para atender e administrar melhor.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[{Icon:ShoppingBag,title:'Pedidos organizados',text:'Receba e acompanhe pedidos com clareza.'},{Icon:ChefHat,title:'Cardápio digital',text:'Produtos, categorias e promoções em poucos passos.'},{Icon:PackageCheck,title:'Estoque e insumos',text:'Controle custos e evite perdas na operação.'},{Icon:BarChart3,title:'Relatórios de gestão',text:'Entenda vendas, lucro e desempenho.'}].map(({Icon,title,text}) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid h-11 w-11 place-items-center rounded-xl bg-orange-50 text-brand-600"><Icon size={21} /></div><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-500">{text}</p></article>)}</div></div></section>

        <section id="como-funciona" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-2"><div><span className="text-sm font-bold text-brand-600">Comece sem complicação</span><h2 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Da configuração ao primeiro pedido.</h2><p className="mt-4 max-w-lg text-slate-600">A Ritmesa prepara a identidade do estabelecimento, organiza o cardápio e acompanha a entrada em operação.</p></div><ol className="space-y-4">{['Cadastramos seu estabelecimento e sua equipe.','Organizamos produtos, categorias e identidade visual.','Publicamos seu cardápio online personalizado.','Você acompanha pedidos e resultados pelo painel.'].map((text,index) => <li key={text} className="flex items-center gap-4 rounded-2xl border border-slate-200 p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-brand-500 font-bold text-white">{index+1}</span><span className="font-semibold text-slate-700">{text}</span></li>)}</ol></div></div></section>

        <section id="contato" className="bg-[#10233f] px-5 py-20 text-white lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><span className="text-sm font-bold text-orange-300">Fale com a Ritmesa</span><h2 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Pronto para colocar seu negócio em um novo ritmo?</h2><p className="mt-4 max-w-lg leading-relaxed text-slate-300">Conte um pouco sobre seu estabelecimento. Nossa equipe entrará em contato para preparar sua operação.</p><ul className="mt-7 space-y-3 text-sm text-slate-200">{['Atendimento para diferentes tipos de food service','Configuração acompanhada pela nossa equipe','Cardápio com a identidade do seu estabelecimento'].map(text => <li key={text} className="flex items-center gap-2"><Check size={17} className="text-orange-300" />{text}</li>)}</ul></div>{sent ? <div className="flex min-h-80 flex-col items-center justify-center rounded-3xl bg-white p-8 text-center text-slate-900"><div className="grid h-14 w-14 place-items-center rounded-full bg-emerald-100 text-emerald-600"><Check size={28} /></div><h3 className="mt-5 text-xl font-bold">Contato recebido!</h3><p className="mt-2 text-sm text-slate-500">A equipe Ritmesa falará com você em breve.</p></div> : <form onSubmit={submit} className="rounded-3xl bg-white p-5 text-slate-900 shadow-2xl sm:p-7"><div className="grid gap-4 sm:grid-cols-2">{[['nome','Seu nome','Como podemos chamar você?'],['estabelecimento','Estabelecimento','Nome do seu negócio'],['telefone','WhatsApp','(00) 99999-9999'],['email','E-mail','voce@email.com'],['cidade','Cidade','Sua cidade']].map(([name,label,placeholder]) => <label key={name} className={`text-sm font-semibold ${name === 'cidade' ? 'sm:col-span-2' : ''}`}>{label}<input required={['nome','estabelecimento','telefone'].includes(name)} value={form[name as keyof typeof form]} onChange={(e) => setForm(current => ({...current,[name]:e.target.value}))} className="mt-2 w-full rounded-xl border border-slate-200 px-3.5 py-3 text-sm outline-none focus:border-brand-500" placeholder={placeholder} /></label>)}</div><label className="mt-4 block text-sm font-semibold">O que você procura?<textarea value={form.mensagem} onChange={(e) => setForm(current => ({...current,mensagem:e.target.value}))} className="mt-2 h-24 w-full resize-none rounded-xl border border-slate-200 p-3.5 text-sm outline-none focus:border-brand-500" placeholder="Conte um pouco sobre sua operação" /></label><button disabled={sending} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-brand-500 px-5 py-3.5 font-bold text-white hover:bg-brand-600 disabled:opacity-60">{sending ? 'Enviando...' : <>Quero conhecer a Ritmesa <ArrowRight size={18} /></>}</button></form>}</div></section>
      </main>
      <footer className="border-t border-slate-200 bg-white px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 text-center sm:flex-row sm:text-left"><div className="flex items-center gap-2"><img src="/brand/ritmesa-mark.png" alt="" className="h-7 w-7" /><strong>Ritmesa</strong></div><p className="text-xs text-slate-500">Tecnologia para restaurantes venderem e administrarem melhor.</p></div></footer>
    </div>
  );
}
