"""Add combo and cancelamento fields

Revision ID: 3f4eab4dc6ca
Revises: 18563862f462
Create Date: 2026-09-10 17:52:41.187858
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f4eab4dc6ca'
down_revision: Union[str, None] = '18563862f462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opcoes_produto', sa.Column('produto_vinculado_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'opcoes_produto', 'produtos', ['produto_vinculado_id'], ['id'], ondelete='SET NULL')
    op.add_column('pedidos', sa.Column('motivo_cancelamento', sa.Text(), nullable=True))
    op.add_column('pedidos', sa.Column('estornado', sa.Boolean(), nullable=True))
    op.add_column('produtos', sa.Column('is_combo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'is_combo')
    op.drop_column('pedidos', 'estornado')
    op.drop_column('pedidos', 'motivo_cancelamento')
    op.drop_constraint(None, 'opcoes_produto', type_='foreignkey')
    op.drop_column('opcoes_produto', 'produto_vinculado_id')
    # ### end Alembic commands ###
